### ISSUE TITLE
improvement

### ISSUE THREAD

**Issue by sholoomail** [oVoIndia/MultiUpload-Bot#3]
is possible to remove log channel and force sub channel from required vars and add auth users var in app.json .

**Comment by oVo-HxBots** [comment]
Yes

**Comment by sholoomail** [comment]
> 
> 
> Yes

please do it!

**Comment by oVo-HxBots** [comment]
Change branch to rm-fs-lc and deploy...

**Comment by oVo-HxBots** [comment]
Done..
